### ISSUE TITLE
Magic Items Issue in v1.4.0

### ISSUE THREAD

**Issue by DivertedCircle** [RedReign/FoundryVTT-BetterRolls5e#237]
The new update that says Magic Items should work again seems to be having issues. I'm finding that items already on a character sheet aren't generating a proper Better Rolls roll. However, dragging an item off a character sheet to the Items Directory, then back onto the sheet will enable Better Rolls rolls for that newly added item. GIF at https://i.imgur.com/v6s7q0L.gifv

**Comment by ConnorSolo** [comment]
To add to this topic, I'm also having some issues with Better Rolls and Magic Items. In my case, when I try to cast a spell from one of the magic items, nothing happens. No chat message, no resources use, no error message. For some reason, the only ways I can get it to work is by either:

1. Changing the magic item to allow upcasting.
2. Casting the spell while it is out of charges.
3. Disabling the "Make Item Image Auto-roll" option in Better Rolls. 

Hopefully that weird behavior might help narrow down the issue. Thanks!

**Comment by DivertedCircle** [comment]
My players also found that clicking a spell from a Magic Item wasn't generating a roll, though I as DM could click it on their sheet and get it to roll.

**Comment by CarlosFdez** [comment]
Interesting enough, it worked until I updated all my modules, then it broke again. Looked into it, and its a race condition (depends on what order the modules are loaded). Magic Items does not play nice (it doesn't use libwrapper) so my little item patching has to be a bit more aggressive.

Should be fixed in v1.4.1, which I just released.

**Comment by ConnorSolo** [comment]
I downloaded and installed the v1.4.1 update, but, unfortunately, the problem is still persisting in my game. Let me know if I can send you any info to help.

**Comment by CarlosFdez** [comment]
@ConnorSolo easiest way would be to send screenshots of:
1) list of modules installed
2) Magic Items tab of the item you're trying to roll
3) Chat log output screenshot

There's probably some combination I'm not accounting for that I need to know about.

**Comment by CarlosFdez** [comment]
Actually, before you do so, try again. The original bug was indeed fixed in v1.4.1 but there was another one involving the event object. v1.4.3 should have it fixed now, but if it isn't, please share what item you're trying to roll.

**Comment by ConnorSolo** [comment]
Looks like the v1.4.3 update fixed everything on my end! Thanks for the hard work.

**Comment by CarlosFdez** [comment]
Glad to hear it worked! There's still a known bug where advantage/disadvantage modifier keys don't work on spells like scorching ray, but that's something that Magic Items has to fix (they need to pass down the event object). 

For now closing, feel free to make an issue if there's anything new!
